QuanLiNhaHang/Models/Donhang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donhang()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
            this.Chitiethanhtoans = new HashSet<Chitiethanhtoan>();
        }
    
        public string Mã_ĐH { get; set; }
        public string Email { get; set; }
        public int Mã_TT { get; set; }

        [Display(Name = "Địa chỉ")]
        public string Địa_chỉ_người_nhận { get; set; }
        public string SĐT { get; set; }

        public int Tổng_tiền { get; set; }

        [Display(Name = "Ngày tạo")]
        public System.DateTime Ngày_giao { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitiethanhtoan> Chitiethanhtoans { get; set; }
        public virtual Trangthaidonhang Trangthaidonhang { get; set; }
    }
}

QuanLiNhaHang/Controllers/DonhangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using QuanLiNhaHang.Models;

namespace QuanLiNhaHang.Controllers
{
    public class DonhangsController : Controller
    {
        private CT25Team111Entities db = new CT25Team111Entities();

        private List<Chitietdonhang> ShoppingCart = null;

        private void GetShoppingCart()
        {

            if (Session["ShoppingCart"] != null)
                ShoppingCart = Session["ShoppingCart"] as List<Chitietdonhang>;
            else
            {
                ShoppingCart = new List<Chitietdonhang>();
                Session["ShoppingCart"] = ShoppingCart;
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Donhangs
        public ActionResult Index()
        {
            var donhangs = db.Donhangs.Include(d => d.Trangthaidonhang);
            return View(donhangs.ToList());
        }

        // GET: Donhangs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donhang donhang = db.Donhangs.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(donhang);
        }

        // GET: Donhangs/Create
        public ActionResult Create()
        {
            GetShoppingCart();
            ViewBag.Cart = ShoppingCart;
            ViewBag.Mã_TT = new SelectList(db.Trangthaidonhangs, "Mã_TT", "Trạng_thái");
            return View();
        }

        // POST: Donhangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Donhang donhang)
        {
            ValidateDonhang(donhang);
            if (ModelState.IsValid)
            {
                donhang.Ngày_giao = DateTime.Now;
                donhang.Mã_ĐH = Guid.NewGuid().ToString();
                db.Donhangs.Add(donhang);
                db.SaveChanges();
                return RedirectToAction("Index2","Sanphams");
            }

            GetShoppingCart();
            ViewBag.Cart = ShoppingCart;
            ViewBag.Mã_TT = new SelectList(db.Trangthaidonhangs, "Mã_TT", "Trạng_thái", donhang.Mã_TT);
            return View(donhang);
        }
        private void ValidateDonhang (Donhang donhang)
        {
            var regex = new Regex("[0-9]{3}");
            GetShoppingCart();
            if (ShoppingCart.Count == 0)
                ModelState.AddModelError("", "Không có sản phẩm nào trong giỏ hàng!");
            if (!regex.IsMatch(donhang.SĐT))
                ModelState.AddModelError("SĐT", "Sai số điện thoại");
        }

        // GET: Donhangs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donhang donhang = db.Donhangs.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.Mã_TT = new SelectList(db.Trangthaidonhangs, "Mã_TT", "Trạng_thái", donhang.Mã_TT);
            return View(donhang);
        }

        // POST: Donhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Donhang donhang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donhang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            ViewBag.Mã_TT = new SelectList(db.Trangthaidonhangs, "Mã_TT", "Trạng_thái", donhang.Mã_TT);
            return View(donhang);
        }

        // GET: Donhangs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donhang donhang = db.Donhangs.Find(id);
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(donhang);
        }

        // POST: Donhangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Donhang donhang = db.Donhangs.Find(id);
            db.Donhangs.Remove(donhang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLiNhaHang/Views/Donhangs/Create.cshtml
@using QuanLiNhaHang.Models
@model QuanLiNhaHang.Models.Donhang

@{
    ViewBag.Title = "Create";
    var Cart = ViewBag.Cart as List<Chitietdonhang>;
}

<h2>Create</h2>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>eCommerce HTML-5 Template </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="@Url.Content("~/assets/css/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/owl.carousel.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/flaticon.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/slicknav.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/animate.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/magnific-popup.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/fontawesome-all.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/themify-icons.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/slick.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/nice-select.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/style.css")">
</head>
<section class="latest-product-area padding-bottom">
    <div class="container">
        <div class="billing_details">
            <div class="row">
                <div class="col-lg-8">
                    <h3>Billing Details</h3>

                    

                    @using (Html.BeginForm("Create", "Donhangs", FormMethod.Post, new { @class = "row contact_form" }))
                    {
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.AntiForgeryToken()
                          <div class="col-md-6 form-group p_star">
                           @Html.DropDownList("Mã_TT", null, htmlAttributes: new { @class = "form-control", required = true, style = "padding-left:70px" } )
                              @Html.ValidationMessageFor(model => model.Mã_TT, "", new { @class = "text-danger" })
                          <span class="placeholder" data-placeholder="Trạng thái "></span>
                         </div>

                        <div class="col-md-6 form-group p_star">
                            @Html.EditorFor(model => model.SĐT, new { htmlAttributes = new { @class = "form-control", required = true, style = "padding-left:50px" } })
                            @Html.ValidationMessageFor(model => model.SĐT, "", new { @class = "text-danger" })
                            <span class="placeholder" data-placeholder="SĐT"></span>
                            <div class="col-md-10">
                            </div>
                        </div>
                        <div class="col-md-6 form-group p_star">
                            @Html.EditorFor(model => model.Địa_chỉ_người_nhận, new { htmlAttributes = new { @class = "form-control", required = true, style = "padding-left:70px" } })
                            @Html.ValidationMessageFor(model => model.Địa_chỉ_người_nhận, "", new { @class = "text-danger" })
                            <span class="placeholder" data-placeholder="Address"></span>
                        </div>
                        <div class="col-md-6 form-group p_star">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", required = true, style = "padding-left:100px" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            <span class="placeholder" data-placeholder="Email Address"></span>
                        </div>

                        <div class="creat_account">
                            <input type="checkbox" id="f-option4" name="selector" required>
                            <label for="f-option4">I’ve read and accept the </label>
                            <a href="#">terms &amp; conditions*</a>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Place Order" class="btn btn-default" style="color: white" />
                            </div>
                        </div>
                    }
                </div>
                <div class="col-lg-4">
                    <div class="order_box">
                        <h2>Your Order</h2>
                        <ul class="list">
                            <li>
                                <a href="#">
                                    Product
                                    <span>Total</span>
                                </a>
                            </li>
                            @foreach (var item in Cart)
                            {
                                <li>
                                    <a href="@Url.Action("Details","Sanphams", new {item.Sanpham.Mã_SP })">
                                        @item.Sanpham.Tên_món_ăn
                                        <span class="middle">x @item.Số_lượng</span>
                                        <span class="last">@(item.Sanpham.Giá_tiền * item.Số_lượng)đ</span>
                                    </a>
                                </li>
                            }

                        </ul>
                        <ul class="list list_2">
                            <li>
                                <a href="#">
                                    Total
                                    <span>@(Cart.Sum(c => c.Sanpham.Giá_tiền * c.Số_lượng).ToString("N0"))đ</span>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>



        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLiNhaHang/Views/Donhangs/Delete.cshtml
@model QuanLiNhaHang.Models.Donhang

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Donhang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Địa_chỉ_người_nhận)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Địa_chỉ_người_nhận)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SĐT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SĐT)
        </dd>

        

      

        <dt>
            @Html.DisplayNameFor(model => model.Ngày_giao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngày_giao)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Trangthaidonhang.Trạng_thái)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthaidonhang.Trạng_thái)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuanLiNhaHang/Views/Donhangs/Details.cshtml
@model QuanLiNhaHang.Models.Donhang

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Donhang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Địa_chỉ_người_nhận)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Địa_chỉ_người_nhận)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SĐT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SĐT)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Ngày_giao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngày_giao)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Trangthaidonhang.Trạng_thái)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trangthaidonhang.Trạng_thái)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Mã_ĐH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QuanLiNhaHang/Views/Donhangs/Edit.cshtml
@model QuanLiNhaHang.Models.Donhang

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Donhang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Mã_ĐH)

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mã_TT, "Mã_TT", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Mã_TT", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mã_TT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Địa_chỉ_người_nhận, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Địa_chỉ_người_nhận, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Địa_chỉ_người_nhận, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SĐT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SĐT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SĐT, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Ngày_giao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngày_giao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngày_giao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLiNhaHang/Views/Donhangs/Index.cshtml
@model IEnumerable<QuanLiNhaHang.Models.Donhang>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Địa_chỉ_người_nhận)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SĐT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Ngày_giao)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Trangthaidonhang.Trạng_thái)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Địa_chỉ_người_nhận)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SĐT)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Ngày_giao)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Trangthaidonhang.Trạng_thái)
    </td>
    <td>
        @foreach (var details in item.Chitietdonhangs)
                {
                    @details.Sanpham.Tên_món_ăn <span>x</span> @details.Số_lượng <br />
                }
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Mã_ĐH }) |
        @Html.ActionLink("Details", "Details", new { id = item.Mã_ĐH }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Mã_ĐH })
    </td>
</tr>
}

</table>