QuanLiNhaHang/Models/Sanpham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
            this.Chitietgiohangs = new HashSet<Chitietgiohang>();
        }
    
        public string Mã_SP { get; set; }
        public string Mã_loại_SP { get; set; }
        public string Tên_món_ăn { get; set; }
        public int Số_lượng { get; set; }
        public int Giá_tiền { get; set; }
        public string Mô_tả { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietgiohang> Chitietgiohangs { get; set; }
        public virtual Loaisanpham Loaisanpham { get; set; }
    }
}

QuanLiNhaHang/Controllers/SanphamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Transactions;
using QuanLiNhaHang.Models;

namespace QuanLiNhaHang.Controllers
{
    [Authorize]
    public class SanphamsController : Controller
    {
        private CT25Team111Entities db = new CT25Team111Entities();
        [Authorize(Roles = "Admin")]
        // GET: Sanphams
        public ActionResult Index()
        {
            var sanphams = db.Sanphams.Include(s => s.Loaisanpham);
            return View(sanphams.ToList());
        }

        // for khachhang
        [AllowAnonymous]
        public ActionResult Index2()
        {
            var sanphams = db.Sanphams.Include(s => s.Loaisanpham);
            return View(sanphams.ToList());
        }
        // hàm search

        [AllowAnonymous]
        public ActionResult Search(String keyword)
        {
            var model = db.Sanphams.ToList();
            model = model.Where(p => p.Tên_món_ăn.ToLower().Contains(keyword.ToLower())).ToList();
            ViewBag.Keyword = keyword;
            return View("Index2", model);

        }
        // GET: Sanphams/Details/5
        [AllowAnonymous]
        public ActionResult Details(string id)

        {
          var model = db.Sanphams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Picture(string Mã_SP)
        {
            var path = Server.MapPath(PICTURE_PATH);
            return File(path + Mã_SP, "images");
        }
        // GET: Sanphams/Create
        public ActionResult Create()
        {

            ViewBag.Mã_loại_SP = new SelectList(db.Loaisanphams, "Mã_loại_SP", "Tên_loại_SP");
            return View();
        }

        // POST: Sanphams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sanpham model, HttpPostedFileBase picture)
        {
            ValidateProduct(model);
            if (ModelState.IsValid)
            {
                if (picture != null)
                {
                    using (var scope = new TransactionScope())
                    {
                        db.Sanphams.Add(model);
                        db.SaveChanges();

                        // store picture
                        var path = Server.MapPath(PICTURE_PATH);
                        picture.SaveAs(path + model.Mã_SP);

                        scope.Complete();
                        return RedirectToAction("Index");
                    }

                }
                else ModelState.AddModelError("", "hình ảnh không được tìm thấy!");
            }

            ViewBag.Mã_loại_SP = new SelectList(db.Loaisanphams, "Mã_loại_SP", "Tên_loại_SP", model.Mã_loại_SP);
            return View(model);
        }
        private const string PICTURE_PATH = "~/Upload/Sanphams/";
        public void ValidateProduct(Sanpham sanpham)
        {
            if (sanpham.Giá_tiền < 0)
                ModelState.AddModelError("Giá_tiền", "Giá tiền phải lớn hơn 0");
            if (sanpham.Số_lượng < 0)
                ModelState.AddModelError("Số_lượng", "Số lượng phải lớn hơn 0");
        }

        // GET: Sanphams/Edit/5
        public ActionResult Edit(string id)
        {
            var model = db.Sanphams.Find(id);
            if (model == null)
            {
                return HttpNotFound();  
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            ViewBag.Mã_loại_SP = new SelectList(db.Loaisanphams, "Mã_loại_SP", "Tên_loại_SP", model.Mã_loại_SP);
            return View(model);
        }

        // POST: Sanphams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Sanpham model, HttpPostedFileBase picture)
        {
            ValidateProduct(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();

                    if (picture != null)
                    {
                        var path = Server.MapPath(PICTURE_PATH);
                        picture.SaveAs(path + model.Mã_SP);
                    }

                    scope.Complete();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Mã_loại_SP = new SelectList(db.Loaisanphams, "Mã_loại_SP", "Tên_loại_SP", model.Mã_loại_SP);
            return View(model);
        }

        // GET: Sanphams/Delete/5
        public ActionResult Delete(string id)
        {

            var model = db.Sanphams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Sanphams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            using (var scope = new TransactionScope())
            {
                var model = db.Sanphams.Find(id);
                db.Sanphams.Remove(model);
                db.SaveChanges();

                var path = Server.MapPath(PICTURE_PATH);
                System.IO.File.Delete(path + model.Mã_SP);

                scope.Complete();
                return RedirectToAction("Index");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLiNhaHang/Views/Sanphams/Create.cshtml
@model QuanLiNhaHang.Models.Sanpham

@{
    ViewBag.Title = "Create";
}

<h4>Tạo mới sản phẩm</h4>


@using (Html.BeginForm("Create", "Sanphams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Mã_SP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mã_SP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mã_SP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mã_loại_SP, "Mã_loại_SP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Mã_loại_SP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mã_loại_SP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tên_món_ăn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tên_món_ăn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tên_món_ăn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Số_lượng, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Số_lượng, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Số_lượng, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Giá_tiền, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group ">
                    @Html.EditorFor(model => model.Giá_tiền, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">vnđ</span>
                </div>
                @Html.ValidationMessageFor(model => model.Giá_tiền, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mô_tả, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mô_tả, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mô_tả, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="IMG">Hình ảnh</label>
            <div class="col-md-10">
                <input class="control-label" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/gif, image/jpeg, image/png" />
            </div>
            <img id="Picture" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: 'textarea#Mô_tả',
            menubar: false
        });

        function readPicture(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('img#Picture')
                        .attr('src', e.target.result)

                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

}

QuanLiNhaHang/Views/Sanphams/Delete.cshtml
    @model QuanLiNhaHang.Models.Sanpham

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sanpham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên món ăn
        </dt>
        <dd>
            @Model.Tên_món_ăn
        </dd>
        <dt>
            Số lượng
        </dt>
        <dd>
            @Model.Số_lượng
        </dd>
        <dt>
            Giá tiền
        </dt>
        <dd>
            @Model.Giá_tiền.ToString("N0") vnđ
        </dd>
        <dt>
            Mô tả
        </dt>
        <dd>
            @MvcHtmlString.Create(Model.Mô_tả)
        </dd>
        <dt>
            Tên loại SP
        </dt>
        <dd>
            @Model.Loaisanpham.Tên_loại_SP
        </dd>
        <dt>
            Hình ảnh
        </dt>
        <dd>
            <img src="@Url.Action("Picture", new {Model.Mã_SP })" />
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuanLiNhaHang/Views/Sanphams/Details.cshtml
@model QuanLiNhaHang.Models.Sanpham

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<h2 style="padding-left: 10px; color: #ff7315;"><a href="@Url.Action("Details", new { Model.Mã_SP })">@Model.Tên_món_ăn</a></h2>

<div class="row wow fadeIn" style="visibility: visible; animation-name: fadeIn;">

    <!--Grid column-->
    <div class="col-md-3 mb-2" style="margin-right: 10px">

        <img src="@Url.Action("Picture", new {Model.Mã_SP })" class="img-fluid">

    </div>
    <!--Grid column-->
    <!--Grid column-->
    <div class="col-md-3 mb-3">

        <!--Content-->
        <div class="p-4">

            <h3 class="title">
                <a href="@Url.Action("Details", new { id = Model.Mã_SP })">
                    <span class="badge purple mr-1" style="color: #ff7315">@Model.Loaisanpham.Tên_loại_SP</span>
                </a>
                <a href="@Url.Action("Index2", "SanPhams")">
                    <span class="badge blue mr-1">New</span>
                </a>
            </h3>

            <p class="lead">
                <span class="price">@Model.Giá_tiền.ToString("N")đ</span>
            </p>

            <p class="lead font-weight-bold">Mô tả</p>

            <p>
                @Model.Mô_tả
            </p>

            <form action="@Url.Action("Create", "ShoppingCart")" method="post">
                <input type="hidden" name="Mã_SP" value="@Model.Mã_SP" />
                <div class="d-flex justify-content-left">
                    <!-- Default input -->
                    <input name="Số_lượng" type="number" value="1" min="1" aria-label="Search" class="form-control" style="width: 70px">
                    <input type="submit" class="btn btn-primary btn-md my-0 p waves-effect waves-light" value="Add to cart" />


                </div>

            </form>
        </div>
        <!--Content-->

    </div>
    <!--Grid column-->

</div>

QuanLiNhaHang/Views/Sanphams/Edit.cshtml
@model QuanLiNhaHang.Models.Sanpham

@{
    ViewBag.Title = "Edit";
}

<h4>Chỉnh sửa @Model.Tên_món_ăn</h4>


@using (Html.BeginForm("Edit", "Sanphams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Mã_SP)
    <div class="form-group">    
        @Html.LabelFor(model => model.Mã_SP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Mã_loại_SP", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Mã_loại_SP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mã_loại_SP, "Mã_loại_SP", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tên_món_ăn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tên_món_ăn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tên_món_ăn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tên_món_ăn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tên_món_ăn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Số_lượng, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Số_lượng, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Số_lượng, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Giá_tiền, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="input-group ">
                @Html.EditorFor(model => model.Giá_tiền, new { htmlAttributes = new { @class = "form-control" } })
                <span class="input-group-addon">vnđ</span>
            </div>
            @Html.ValidationMessageFor(model => model.Giá_tiền, "", new { @class = "text-danger" })
        </div>
    </div>
        
    <div class="form-group">
        @Html.LabelFor(model => model.Mô_tả, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Mô_tả, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Mô_tả, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="IMG">Hình ảnh</label>
        <div class="col-md-10">
            <input class="control-label" type="file" name="Picture" id="IMG" onchange="readPicture(this)" accept="image/gif, image/jpeg, image/png" />
        </div>
        <img id="Picture" src="@Url.Action("Picture" , new {Model.Mã_SP })" />
    </div>
   
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: 'textarea#Mô_tả',
            menubar: false
        });

        function readPicture(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('img#Picture')
                        .attr('src', e.target.result)

                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>

}

QuanLiNhaHang/Views/Sanphams/Edit2.cshtml
@model QuanLiNhaHang.Models.Sanpham

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sanpham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Mã_SP)

        <div class="form-group">
            @Html.LabelFor(model => model.Mã_loại_SP, "Mã_loại_SP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Mã_loại_SP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mã_loại_SP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tên_món_ăn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tên_món_ăn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tên_món_ăn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Số_lượng, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Số_lượng, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Số_lượng, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Giá_tiền, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Giá_tiền, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Giá_tiền, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mô_tả, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mô_tả, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mô_tả, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLiNhaHang/Views/Sanphams/Index2.cshtml
@model IEnumerable<QuanLiNhaHang.Models.Sanpham>
@{
    ViewBag.Title = "Home Page";
}

<!-- services -->
<div class="services" id="services">
    <div class="container">
        <div class="agile-heading">
            <h3 class="w3l-title">Our Services</h3>
        </div>
        <div class="wthree-services-grids">
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-cutlery" aria-hidden="true"></i>
                        <h4>BEST COOKS</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-car" aria-hidden="true"></i>
                        <h4>FREE PARKING</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-spoon" aria-hidden="true"></i>
                        <h4>FRESH FOOD</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        <h4>Excellent</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="wthree-services-grids services-grids1">
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-money" aria-hidden="true"></i>
                        <h4>Best Price</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-birthday-cake" aria-hidden="true"></i>
                        <h4>BIRTHDAY PARTY</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-credit-card" aria-hidden="true"></i>
                        <h4>Easy Payment</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 wthree-services">
                <div class="wthree-services-grid">
                    <div class="wthree-services-info">
                        <i class="fa fa-bullhorn" aria-hidden="true"></i>
                        <h4>Hotel Popular</h4>
                        <div class="w3ls-border"> </div>
                    </div>
                    <div class="wthree-services-captn">
                        <h4>Glorious</h4>
                        <p>Aenean pulvinar ac enimet posuere tincidunt velit Utin tincidunt</p>
                    </div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //services -->

<!-- menu-section -->
<div class="menu-w3l" id="menu">
    <h3 class="w3l-title">All Product</h3>
    <ul id="flexiselDemo1">
        @foreach (var sanpham in Model)
        {
    <li>
        <div class="w3layouts_banner_bottom_left">
            <a href="@Url.Action("Details", new {id=sanpham.Mã_SP })">
                <img src="@Url.Action("Picture" , "Sanphams", new { sanpham.Mã_SP })" width="300px" height="220px" alt=" demo picture " />
            </a>
            <h4>@sanpham.Tên_món_ăn --- <span>@sanpham.Giá_tiền.ToString("N0") vnđ</span></h4>

        </div>
    </li>}

    </ul>
</div>
<!-- //menu-section -->

QuanLiNhaHang/Views/Sanphams/Indexhome.cshtml
@model IEnumerable<QuanLiNhaHang.Models.Sanpham>
@{
    ViewBag.Title = "Home index";
}

<!-- services -->

<!-- //services -->

<!-- menu-section -->
<div class="menu-w3l" id="menu">
    <h3>@(ViewBag.Keyword!=null?"Search Results":"All Products")</h3>
    <ul id="flexiselDemo1">
        @foreach (var sanpham in Model)
        {
    <li>
        <div class="w3layouts_banner_bottom_left">
            <a href="@Url.Action("Details", new {id=sanpham.Mã_SP })">
                <img src="@Url.Action("Picture" , "Sanphams", new { sanpham.Mã_SP })" width="300px" height="220px" alt=" demo picture " />
            </a>
            <h4><a href="@Url.Action("Details", new {id=sanpham.Mã_SP })">@sanpham.Tên_món_ăn</a>
    --- <span>@sanpham.Giá_tiền.ToString("N0") vnđ</span>
</h4>

        </div>
    </li>}

    </ul>
</div>
<!-- //menu-section -->